### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by elwayman02** [miragejs/ember-cli-mirage#2496] opened 2023-04-10 23:14 UTC
What's the timeline on getting a new stable release of this package? There are a few alpha versions, but it's not clear when v3 is planned to go out. If that's a ways out still, can we get some basic maintenance on the dependencies for the 2.x release series? For example, `ember-auto-import` v1 is still being required by the latest stable release, when most apps want to be on v2 at this point.

**Comment by cah-brian-gantzler** [comment] 2023-05-03 21:08
According to the https://github.com/miragejs/ember-cli-mirage/issues/2458. it was fixed in MirageJS, but hasnt been released (at the time of the comment), would have to look it mirageJS was released, then could bump the version here.

@SergeAstapov was doing a lot of the releases here I think

**Comment by cah-brian-gantzler** [comment] 2023-05-03 21:13
Looks like that fix is in 0.1.46 and 0.1.47    Was wondering how I was using it an its because I pin some versions. So in my app I have this in the package.json (using yarn). This is how I am getting 0.1.47 into my app. As you can see I have to do that for a few other addons that also either need upgraded, or down graded (for example there are addons using ember modifier 4, but since not all are updated, I have to force them down to 3).  (I think some of these may have been needed at one time but no longer, ie ember-cli-babel I think can be removed)
```
  "resolutions": {
    "miragejs": "~0.1.47",
    "@embroider/macros": "^1.10.0",
    "@embroider/util": "^1.10.0",
    "ember-cli-babel": "^7.26.1",
    "ember-modifier": "^3.2.7",
    "@fortawesome/fontawesome-svg-core": "1.2.35"
  }
``

**Comment by elwayman02** [comment] 2023-05-04 00:36
@cah-brian-gantzler what is currently blocking the alpha versions from being considered stable?

**Comment by cah-brian-gantzler** [comment] 2023-05-04 13:20
I think at the time it was just getting people to use it and see if there was any issues (I have been on the alpha for a long time). Im thinking there is no reason not to. 

Given the changes coming in Ember Data and the fact that the create server from Mirage is more exposed now and ember-auto-import, I have been wanting to create a project using Mirage that does not use ember-cli-mirage at all. Not sure what need there is for this addon anymore. Just a personal FYI

**Comment by elwayman02** [comment] 2023-05-22 21:28
@cah-brian-gantzler I think it would make sense to move forward and release the stable version at this point. Whether or not ember-cli-mirage can be completely replaced by direct miragejs usage is another matter altogether; we should still make sure the last release of this package is stable if and when a decision is made to deprecate it in favor of that approach.

**Comment by cah-brian-gantzler** [comment] 2023-06-01 14:27
@SergeAstapov You were doing a lot of the releases back then, would you have time to make the alpha version a real release?

**Comment by Yelinz** [comment] 2023-09-21 08:24
The problem is ember-cli-mirage is in a subdirectory, so for some tools as yarn v1, you cannot even install the latest commit. Not even with a tool like [gitpkg](https://github.com/EqualMa/gitpkg)

**Comment by Yelinz** [comment] 2023-09-22 12:50
https://github.com/miragejs/ember-cli-mirage/blob/07e2500a3c17611bc4dce35ec69bb5edd2424f6d/packages/ember-cli-mirage/package.json#L44-L46
seems v2 to me or am i missing something

Also gitpkg just doesnt seem to work, as it returns a 500. Not sure if the problem is from ember-cli-mirage or gitpkg https://gitpkg.now.sh/miragejs/ember-cli-mirage/packages/ember-cli-mirage?master

**Comment by bartocc** [comment] 2023-09-26 08:28
Hi folks,

What about cutting a new alpha.4 release?
alpha.3 was released in April. Much has happened since!

**Comment by SergeAstapov** [comment] 2023-10-01 03:27
v3.0.0-alpha.5 has been published. Please let me know if you face any issues!

**Comment by bartocc** [comment] 2023-10-02 08:57
Thx @SergeAstapov

**Comment by SergeAstapov** [comment] 2023-10-05 03:46
v3.0.0 is out https://github.com/miragejs/ember-cli-mirage/releases/tag/v3.0.0

**Closed by SergeAstapov** 2023-10-05 03:46 UTC
