### ISSUE TITLE
Could not find module `@miragejs/server` imported from `ember-cli-mirage/response`

### ISSUE THREAD

**Issue by rg-galieva** [miragejs/ember-cli-mirage#1686] opened 2019-07-10 22:33 UTC
After upgrading from 1.0.0 -> 1.1.0-beta.4 I'm getting this error:
```
vendor.js:255 Uncaught Error: Could not find module `@miragejs/server` imported from `ember-cli-mirage/response`
    at missingModule (vendor.js:255)
    at findModule (vendor.js:266)
    at Module.findDeps (vendor.js:176)
    at findModule (vendor.js:270)
    at Module.findDeps (vendor.js:176)
    at findModule (vendor.js:270)
    at Module.findDeps (vendor.js:176)
    at findModule (vendor.js:270)
    at requireModule (vendor.js:32)
    at resolveInitializer (vendor.js:195665)
```

I see that in v1.1.0-beta.1 core logic was extracted to @miragejs/server.

**Comment by samselikoff** [comment] 2019-07-12 14:24
@rg-galieva I wasn't able to reproduce in a new app, but it looks like you might have a node_modules issue... could you try wiping your local `node_modules` and re-running `npm install` (or `yarn install`)?

**Comment by rg-galieva** [comment] 2019-07-16 17:33
@samselikoff Thanks for checking it. I've tried to clean up node_modules, but still getting the same error.

**Comment by samselikoff** [comment] 2019-07-16 18:32
Any chance you could upload a simplified reproduction to github? Without it it's hard to diagnose the bug 🙂

**Comment by rg-galieva** [comment] 2019-07-18 03:00
My "broken" project has so many dependencies, impossible to share. 
I've tried to reproduce this issue with a brand new app, everything works as expected.

Also, I found this issue #1548
I'm getting the same errors in the "broken" app version when rolling back to v1.0.0. But again everything is ok with a "new" app.

Suggested [fix](https://github.com/samselikoff/ember-cli-mirage/issues/1548#issuecomment-500149439) worked:
```
let app = new EmberApp(defaults, {
    // Add options here
    autoImport: {
      forbidEval: true,
    }
  });
```

So I'm assuming that was the source of the problem since in both cases along with a missing dependency error there is an Uncaught EvalError:
`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive`.

And forbidEval is for "If you need to comply with a strict Content Security Policy (CSP), you can set forbidEval: true".

However, I'm still suspicious :) 
I've started facing this problem only after ember-cli-mirage upgrade (considering tons of other dependencies, same conditions, same content policy).

**Comment by PritamBhanji08** [comment] 2019-08-21 07:23
thanks @rg-galieva it worked for me.

**Comment by samselikoff** [comment] 2019-09-05 21:40
Could y'all give 1.1.1 a try and see if this is still an issue?

**Comment by SYU15** [comment] 2019-11-25 23:01
@samselikoff I still needed this fix with `mirage` version `1.1.4`.

**Comment by samselikoff** [comment] 2019-12-14 18:02
@SYU15 sorry about that. Still having trouble reproducing, could you upload a repo with a reproduction? Or provide versions of ember/ember-cli/mirage? (Fastest way to get help is with reproduction)

**Comment by samselikoff** [comment] 2020-01-30 20:11
I'm closing for now but please post here and I can re-open if you're still having issues. If so, please provide a reproduction or else I can't really help diagnose! 🙇

**Closed by samselikoff** 2020-01-30 20:11 UTC
Labels: Bug report
