### ISSUE TITLE
Doesn't work with `ember-auto-import` V2

### ISSUE THREAD

**Issue by villander** [miragejs/ember-cli-mirage#2234] opened 2021-10-05 19:33 UTC
ember-cli: 3.28.1
ember-cli-mirage: 2.2.0
ember-auto-import: 2.2.0

![image](https://user-images.githubusercontent.com/10222774/136090575-7c67ad22-027e-4caa-b193-e5f1fe0b76d9.png)

Stack error:

```
=================================================================================

ENV Summary:

  TIME: Tue Oct 05 2021 16:28:37 GMT-0300 (Brasilia Standard Time)
  TITLE: ember
  ARGV:
  - /Users/villander/.nvm/versions/node/v14.17.5/bin/node
  - /Users/villander/Projects/sunflower/node_modules/.bin/ember
  - serve
  EXEC_PATH: /Users/villander/.nvm/versions/node/v14.17.5/bin/node
  TMPDIR: /var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/yarn--1633462098989-0.7082144363589473
  - /Users/villander/Projects/sunflower/node_modules/.bin
  - /Users/villander/.config/yarn/link/node_modules/.bin
  - /Users/villander/Projects/sunflower/node_modules/.bin
  - /Users/villander/.nvm/versions/node/v14.17.5/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /Users/villander/.nvm/versions/node/v14.17.5/lib/node_modules/npm/bin/node-gyp-bin
  - /Users/villander/.nvm/versions/node/v14.17.5/bin/node_modules/npm/bin/node-gyp-bin
  - /Users/villander/.rbenv/shims
  - /Users/villander/.rbenv/bin
  - /Users/villander/.nvm/versions/node/v14.17.5/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Library/Apple/usr/bin
  PLATFORM: darwin x64
  FREEMEM: 82059264
  TOTALMEM: 17179869184
  UPTIME: 25517
  LOADAVG: 2.884765625,2.6923828125,2.67578125
  CPUS:
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.17.2
  - brotli: 1.0.9
  - cldr: 39.0
  - icu: 69.1
  - llhttp: 2.1.3
  - modules: 83
  - napi: 8
  - nghttp2: 1.42.0
  - node: 14.17.5
  - openssl: 1.1.1k
  - tz: 2021a
  - unicode: 13.0
  - uv: 1.41.0
  - v8: 8.4.371.23-node.76
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: webpack returned errors to ember-auto-import
    at /Users/villander/Projects/sunflower/client/node_modules/ember-auto-import/js/webpack.js:345:32
    at finalCallback (/Users/villander/Projects/sunflower/node_modules/webpack/lib/Compiler.js:434:32)
    at /Users/villander/Projects/sunflower/node_modules/webpack/lib/Compiler.js:498:17
    at /Users/villander/Projects/sunflower/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/villander/Projects/sunflower/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/villander/Projects/sunflower/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.storeBuildDependencies (/Users/villander/Projects/sunflower/node_modules/webpack/lib/Cache.js:122:37)
    at /Users/villander/Projects/sunflower/node_modules/webpack/lib/Compiler.js:494:19
    at Hook.eval [as callAsync] (eval at create (/Users/villander/Projects/sunflower/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/villander/Projects/sunflower/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
  - code: [undefined]
  - codeFrame: webpack returned errors to ember-auto-import
  - errorMessage: webpack returned errors to ember-auto-import
        at WebpackBundler (ember-auto-import-webpack)
-~- created here: -~-
    at new Plugin (/Users/villander/Projects/sunflower/client/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new WebpackBundler (/Users/villander/Projects/sunflower/client/node_modules/ember-auto-import/js/webpack.js:88:9)
    at AutoImport.makeBundler (/Users/villander/Projects/sunflower/client/node_modules/ember-auto-import/js/auto-import.js:96:16)
    at AutoImport.addTo (/Users/villander/Projects/sunflower/client/node_modules/ember-auto-import/js/auto-import.js:116:51)
    at Class.postprocessTree (/Users/villander/Projects/sunflower/client/node_modules/ember-auto-import/js/index.js:47:55)
    at /Users/villander/Projects/sunflower/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
    at addonProcessTree (/Users/villander/Projects/sunflower/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/villander/Projects/sunflower/node_modules/ember-cli/lib/broccoli/ember-app.js:867:12)
    at EmberApp.toTree (/Users/villander/Projects/sunflower/node_modules/ember-cli/lib/broccoli/ember-app.js:1690:17)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: webpack returned errors to ember-auto-import
        at WebpackBundler (ember-auto-import-webpack)
-~- created here: -~-
    at new Plugin (/Users/villander/Projects/sunflower/client/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new WebpackBundler (/Users/villander/Projects/sunflower/client/node_modules/ember-auto-import/js/webpack.js:88:9)
    at AutoImport.makeBundler (/Users/villander/Projects/sunflower/client/node_modules/ember-auto-import/js/auto-import.js:96:16)
    at AutoImport.addTo (/Users/villander/Projects/sunflower/client/node_modules/ember-auto-import/js/auto-import.js:116:51)
    at Class.postprocessTree (/Users/villander/Projects/sunflower/client/node_modules/ember-auto-import/js/index.js:47:55)
    at /Users/villander/Projects/sunflower/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
    at addonProcessTree (/Users/villander/Projects/sunflower/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/villander/Projects/sunflower/node_modules/ember-cli/lib/broccoli/ember-app.js:867:12)
    at EmberApp.toTree (/Users/villander/Projects/sunflower/node_modules/ember-cli/lib/broccoli/ember-app.js:1690:17)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: ember-auto-import-webpack
  - nodeName: WebpackBundler
  - originalErrorMessage: webpack returned errors to ember-auto-import
  - stack: Error: webpack returned errors to ember-auto-import
    at /Users/villander/Projects/sunflower/client/node_modules/ember-auto-import/js/webpack.js:345:32
    at finalCallback (/Users/villander/Projects/sunflower/node_modules/webpack/lib/Compiler.js:434:32)
    at /Users/villander/Projects/sunflower/node_modules/webpack/lib/Compiler.js:498:17
    at /Users/villander/Projects/sunflower/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/villander/Projects/sunflower/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/villander/Projects/sunflower/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.storeBuildDependencies (/Users/villander/Projects/sunflower/node_modules/webpack/lib/Cache.js:122:37)
    at /Users/villander/Projects/sunflower/node_modules/webpack/lib/Compiler.js:494:19
    at Hook.eval [as callAsync] (eval at create (/Users/villander/Projects/sunflower/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/villander/Projects/sunflower/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)

=================================================================================
```

**Comment by villander** [comment] 2021-10-19 20:48
@samselikoff @ef4 any tips here?

**Comment by ef4** [comment] 2021-10-19 21:29
Just adding these dependencies to a new app doesn't reproduce this problem. If you can figure out a minimal reproduction I can take a look.

**Comment by cah-briangantzler** [comment] 2021-11-22 16:35
My app is using ember-auto-import 2 and ember-cli-mirage just for a sanity check.

**Comment by angelayanpan** [comment] 2021-12-07 22:25
also running into this issue

**Comment by SergeAstapov** [comment] 2021-12-14 03:01
@villander @angelayanpan could you please create a minimal reproduction issue so we can debug?

**Comment by acorncom** [comment] 2023-09-11 09:11
@villander looks like a number of folks are using this with ember-auto-import v2 (especially with the v3 alphas). I'll close this issue for now, feel free to ping if we need to reopen

**Closed by acorncom** 2023-09-11 09:11 UTC
