### ISSUE TITLE
adding "root: false" to serializer returns nothing

### ISSUE THREAD

**Issue by mdbr000** [miragejs/ember-cli-mirage#1720] opened 2019-08-17 22:17 UTC
Running the latest ember-cli-mirage with ember-cli 3.11

In mirage, if one adds "root: false" [as suggested in the docs](https://www.ember-cli-mirage.com/docs/api/modules/lib/serializer~Serializer#root) in order to receive a response that has no root in the JSON, nothing is returned.  There's not even an error that can be caught on the route side in the error hook after a findAll, or findRecord call.  Removing "root: false" causes a response to be returned, but it has the unwanted root property in the JSON.

`mirage/serializers/application.js`
```javascript
import { Serializer } from 'ember-cli-mirage';

export default Serializer.extend({
  root: false
});
```
### ^ that returns nothing

`mirage/serializers/application.js`
```javascript
import { Serializer } from 'ember-cli-mirage';

export default Serializer.extend({
  //root: false
});
```
### ^ that returns data, but with the unwanted root

**Comment by samselikoff** [comment] 2019-09-02 15:33
@mdbr000 seems strange... could you provide a simplified reproduction?

**Comment by LuisAverhoff** [comment] 2020-01-02 15:39
For me it is even worse, using `root: false` causes my tests to timeout. Removing it lets the test continue normally.

**Comment by samselikoff** [comment] 2020-01-06 19:59
@LuisAverhoff  There might be an error getting swallowed somewhere. Also try setting both `root: false` and `embed: true`. It's an awkward API right now but that might fix it.

If you're still having trouble a reproduction would be the best way for me to help!

**Comment by samselikoff** [comment] 2020-01-30 19:59
Closing for now but let me know if you're still having trouble! I think you might need to set both `embed` and `root`, and also console.log any errors in case you're not seeing them due to asynchrony.

**Closed by samselikoff** 2020-01-30 19:59 UTC
Labels: Bug report
